/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChannelPoint: typeof import('./components/ChannelPoint.vue')['default']
    ConnectDialog: typeof import('./components/dialogs/ConnectDialog.vue')['default']
    Game: typeof import('./components/Game.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
