/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveAlert: typeof import('./components/ActiveAlert.vue')['default']
    AutoMacro: typeof import('./components/AutoMacro.vue')['default']
    ChannelPoint: typeof import('./components/ChannelPoint.vue')['default']
    ConnectDialog: typeof import('./components/dialogs/ConnectDialog.vue')['default']
    CopyButton: typeof import('./components/CopyButton.vue')['default']
    CurrentGame: typeof import('./components/CurrentGame.vue')['default']
    Game: typeof import('./components/Game.vue')['default']
    Macro: typeof import('./components/Macro.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    PowerDialog: typeof import('./components/dialogs/PowerDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
